### ISSUE TITLE
Missing _data folder

### ISSUE THREAD

**Issue by lucasa** [OpenHypervideo/FrameTrail#2]
Hi!
How can i create the "_data" folder to make FrameTrail working?
Or can you commit a hello world sample _data folder?

Thanks
Lucas

**Comment by OpenHypervideo** [comment]
Hi Lucas,
the "_data" folder is generated automatically in the setup process, after you defined the master password (http://frametrail.org/installation.html). If that doesn't work, please check if your server environment meets the requirements / prerequisites (or ask your admin).
We do this automatically (via php) to avoid problems with folder & file permissions (the scripts need write access to the data files in order to save changes).
Please tell me if you got it working or comment here if you need more help.

**Comment by lucasa** [comment]
Thanks for the help!
I was missing the PHP module... duu!
So I'm creating my first project now.

**Comment by lucasa** [comment]
Thanks for the help!
I was missing the PHP module... duu!
So I'm creating my first project now.
