### ISSUE TITLE
Bug: impossible to create new project. Project Json Error

### ISSUE THREAD

**Issue by uwe22** [OpenHypervideo/FrameTrail#26]
downloaded 9.5.1-beta
installed on MAMP on OSX 10.13.3
Entered Master Password
Entered a Project Name and description.
Save produced an error project json cannot be created.
further contact with project manager impossible.
See error in the screenshot.
Please help.

![screen shot 2018-02-26 at 23 58 21](https://user-images.githubusercontent.com/11908297/36677253-0967b9b6-1b51-11e8-85a1-1c3bd16f936d.jpg)

**Comment by OpenHypervideo** [comment]
Please check if the newly created project directory is writable. The setup process is currently being re-implemented, the project level has been removed entirely, simplifying many use cases. If the directory is writable and is still doesn't work, you can try working with the latest development branch version. Unfortunately the setup process there is under construction, meaning it does work, but if there are any problems (like permission errors), you won't get an error message.

**Comment by OpenHypervideo** [comment]
Could you provide me the _index.json at `/_data/projects/_index.json`?

**Comment by uwe22** [comment]
Thank you for the quick reply
I downloaded from git directly in a fresh MAMP htdocs folder.
This is what the structure looks like
![screen shot 2018-02-27 at 00 49 09](https://user-images.githubusercontent.com/11908297/36680047-13d658e2-1b58-11e8-8013-0464ee958ffa.jpg)


[_index.json.zip](https://github.com/OpenHypervideo/FrameTrail/files/1759243/_index.json.zip)
![screen shot 2018-02-27 at 00 43 03](https://user-images.githubusercontent.com/11908297/36679753-58f2128c-1b57-11e8-8173-5aad4b534a16.jpg)

**Comment by OpenHypervideo** [comment]
Please replace your `_/data/projects/_index.json` with the attached file in the ZIP:
[_index.json.zip](https://github.com/OpenHypervideo/FrameTrail/files/1759451/_index.json.zip)

Sorry about the inconvenience. From now on, everything should be fine, including the generation of new projects etc. It's a known bug which wasn't fixed, because that part of the data directory will not exist anymore in the new data structure. I hope we'll be able to merge the new version + format soon into the master branch, but right now it's under heavy development.
Please tell me if it works with the replaced file.

**Comment by uwe22** [comment]
Thank you for your fix.
I was able to access the project manager.
I will play a bit around with it and give you some feed back.
Best regards

**Comment by OpenHypervideo** [comment]
Great, thanks!
