### ISSUE TITLE
video size limit 40 MB - can we adjust this limit?

### ISSUE THREAD

**Issue by iPanini** [OpenHypervideo/FrameTrail#35]
Hi,
Most of our mp4 files are between 500 MB and 1TB.
Can we adjust some setting to allow for larger mp4 files?
Or do we need to cut the mp4 to chunks < 40 MB?
If so does FrameTrail support some way to play the final result of our editing or does this need to be exported back to mp4?

Thanks for helping out!

**Comment by OpenHypervideo** [comment]
I'm gonna reply here instead of the mail as the reply might be helpful for others:

First of all, video files you upload in FrameTrail need to be already optimised for web use. FrameTrail does not do any transcoding / optimisation of the files after uploading. 

A 1 TB video file is by no means suitable for web use. See https://frametrail.org/faq.html#question23 ("How do I make these mp4 files") for some hints. Generally speaking: the smaller, the better. 

You also have the option to upload the videos to a hoster that supports adaptive streaming (like brightcove) and add the videos via pasting the video URL into the resource manager form (the m3u format works as well). They will be detected and usable the same way you are using videos which are uploaded into FrameTrail. 

About the file size limitation: 
FrameTrail does not have any limitations regarding the file size. This limitation stems from your server setup, in that case the PHP setting. See eg. https://stackoverflow.com/questions/2184513/change-the-maximum-upload-file-size or just search "increase file size limit php". 

You could theoretically assemble chunks of videos within one hypervideo which will play like it was one video file, but that functionality requires some manual work and is not fully documented yet. If you decide to do that, please get in touch again. But under normal circumstances (that is, if your goal is just to enable playback and you don't want to programmatically influence the contents) I would not recommend it anyway.

**Comment by iPanini** [comment]
Hi Joscha,
Thanks for helping out.

I'll look into php settings later. I've realized, that my xampp setup in fact is a virtual machine.
So far I'm ok with that, but in fact I don't need this and I guess it's an unnecessary burden form my system.
As every macOS has its own Apache server onboard (you just need to enable it) I would prefer FrameTrail to run in this environment.
(maybe I can just try and copy the actual functioning directory to the onboard Apache htdocs, in fact that should work since there's no database behind it)

I'm looking into creating chunks of my video's that would meet the 40 MB limit.
For this I'm looking into Handbrake. I guess it should be able to do it, just need to find out how.
Since most of the video frames are in fact powerpoint or keynote slides being commented by the narrator, this should not be too problematic.

I'll keep you posted here.

**Comment by OpenHypervideo** [comment]
Yes the onboard Apache server should work fine, as long as the onboad PHP version meets the requirements. And yes you can just copy and paste all data (you might have to correct permissions afterwards). 

As I said, I really don't recommend working with chunks of videos. This requires a lot of manual positioning etc. and will mess with the buffering logic if not done right. If your videos are mostly slides it should be relatively easy to compress / transcode them to a reasonable size. If that affects the quality too much, I'd rather look into video hosting solutions than trying to split up the video files. 

If you let me know (via mail), what your project is about, I might be able to provide more specific help.
