### ISSUE TITLE
Unable to scrub video

### ISSUE THREAD

**Issue by tomberek** [OpenHypervideo/FrameTrail#37]
Any attempt to skip video or scrub to some point in the middle causes the video to restart.

**Comment by OpenHypervideo** [comment]
Can you provide a live link? If not: what's the video source?

**Comment by tomberek** [comment]
I'm running FrameTrail locally, it's an mp4 I made. It plays fine, pause/play work. But attempting to scrub to midpoints causes it to play from beginning. Seems to happen with all mp4's i've tried with, (here's my current example video: https://file-examples.com/wp-content/uploads/2017/04/file_example_MP4_1280_10MG.mp4) . I'm on Chrome/Linux.

No errors noticed in JS console.

**Comment by OpenHypervideo** [comment]
Do you have issues on other sites playing videos? Like the same file in plain HTML5? https://jsfiddle.net/mnp23wf5/1/
If that doesn't work it could be a generic Linux issue with video playback. 
If it does work, you can try to add the video via pasting the video url from above into the url field (it will be detected as a video). If that also doesn't work I would need to see a live demo in order to see what's wrong. Just to be sure: do you have the possibility to test it in a non-Linux environment and in different browsers? Would be interested to see what the problem is, as this hasn't been reported before.

**Comment by tomberek** [comment]
Other forms of video playback work well with Chrome.  Looks like Firefox
works fine and does NOT have the same problem (on Linux). Not sure what
would be different on Chrome.

All of this is running the same backend.

**Comment by OpenHypervideo** [comment]
And you are using Chrome, not Chromium right?

**Comment by tomberek** [comment]
Correct, proper Chrome.

**Comment by OpenHypervideo** [comment]
OK this might be a server side issue: https://stackoverflow.com/questions/35751736/seeking-in-html5-video-with-chrome

**Comment by tomberek** [comment]
Good catch. It’s possible. I was just using the built-in php dev server, it probably doesn’t do the 206 correctly.

**Comment by OpenHypervideo** [comment]
OK I hope this was it then. Let me know if eg. a standard Apache server
works.
